name: algorithms_visualizer
description: A new Flutter project.











version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^4.3.3
  after_layout: ^1.0.7+2
  dots_indicator: ^1.1.0

  
  
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter






flutter:

  
  
  
  uses-material-design: true

  
module:

  androidX: true